version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    ports:
      - 9870:9870
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode1
    hostname: datanode1
    ports:
      - 9864:9864     
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode2
    hostname: datanode2    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  

  datanode3:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode3
    hostname: datanode3    
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env



  datanode4:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode4
    hostname: datanode4
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env




  datanode5:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode5
    hostname: datanode5
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env


  

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    ports:
      - 8088:8088   
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 datanode4:9864 datanode5:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager1
    ports:
      - 8042:8042      
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 datanode4:9864 datanode5:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: bde2020/hadoop-historyserver:latest
    container_name: historyserver
    ports:
      - 8188:8188        
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 datanode4:9864 datanode5:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
 
